name: release:trdl-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  repository_dispatch:
    types: ["release:trdl-release"]
  workflow_dispatch:

jobs:
  release:
    name: Perform werf release using trdl server
    runs-on: ubuntu-22.04
    steps:
      - name: Release with retry
        run: go run cmd/main.go
        env:
          VAULT_ADDR: ${{ secret.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secret.VAULT_TOKEN }}
          TRDL_GIT_TAG: ${{ github.ref_name }}
          TRDL_OPERATION: release
